name: Update SA Public Holidays

on:
  schedule:
    # ACDT (UTC+10:30) — October to March → 01:30 UTC = 12:00 PM ACDT
    - cron: '30 1 1 10,11,12,1,2,3 *'
    # ACST (UTC+9:30) — April to September → 02:30 UTC = 12:00 PM ACST
    - cron: '30 2 1 4,5,6,7,8,9 *'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests httpx

      - name: Run update script
        run: python update_sa_holidays.py
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sa_public_holidays.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SA public holidays calendar - quarterly update" && git push)
