name: Update SA Public Holidays

on:
  schedule:
    # Run at 10:30 AM Adelaide time for each quarter
    # January (ACDT: UTC+10:30) - 00:00 UTC
    - cron: '30 0 1 1 *'
    # April (First few days might be ACDT, rest is ACST: UTC+9:30) - using ACST
    - cron: '30 1 1 4 *'
    # July (ACST: UTC+9:30) - 01:00 UTC
    - cron: '30 1 1 7 *'
    # October (First few days might be ACST, rest is ACDT: UTC+10:30) - using ACST
    - cron: '30 1 1 10 *'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests httpx

      - name: Run update script
        run: python update_sa_holidays.py
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sa_public_holidays.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SA public holidays calendar - quarterly update" && git push) 